### ISSUE TITLE
Chart.vueを楽譜表示部分とフォーム部分とで分割する

### ISSUE THREAD

**Issue by dowdiness** [obregonia1/visible_scratch_skillz#129]
現在楽譜のUIが1つのVueファイルにまとめられており再利用が難しい状態です。
楽譜のリスト表示の際に楽譜の表示を出来るようにするため分割する必要があると思います。

**Comment by obregonia1** [comment]
> 楽譜のリスト表示の際に楽譜の表示を出来るようにする

なるほどですね〜検討します！
